In [1]:
import numpy as np
import pandas as pd
import os
from utils.config import path_dir_descriptor, path_dir_data, path_dir_tsOutput, Poly_degree, path_file_mapping
from datapre.preprocessTools import loadTrainingDataFeatures
from sklearn import preprocessing
# Load feature matrix

iD, X = loadTrainingDataFeatures(isNormalized=False)

In [2]:

print(iD)
print(iD.size)

[['Sub-A_CA-A_Hyd-A_LigS-A']
 ['Sub-A_CA-A_Hyd-A_LigS-B']
 ['Sub-A_CA-A_Hyd-A_LigS-C']
 ...
 ['Sub-AC_Base-E_Oxo-F_LigA-D']
 ['Sub-AC_Base-E_Oxo-F_LigA-E']
 ['Sub-AC_Base-E_Oxo-F_LigA-F']]
41760


In [4]:
print(X)
print(X.shape)

[[ 5.01     1.96     6.2     ... -0.38617 -0.29817 -0.01879]
 [ 5.01     1.96     6.2     ... -0.36939 -0.32463 -0.04688]
 [ 5.01     1.96     6.2     ... -0.39388 -0.29351 -0.01451]
 ...
 [ 4.82     2.65     5.36    ... -0.44773 -0.28832 -0.01581]
 [ 4.82     2.65     5.36    ... -0.43029 -0.28423 -0.01779]
 [ 4.82     2.65     5.36    ... -0.39028 -0.27518 -0.02313]]
(41760, 32)


In [39]:

X1 = X[1:50000,:]
print(X1)

[[ 5.01     1.96     6.2     ... -0.36939 -0.32463 -0.04688]
 [ 5.01     1.96     6.2     ... -0.39388 -0.29351 -0.01451]
 [ 5.01     1.96     6.2     ... -0.41186 -0.29588 -0.00867]
 ...
 [ 4.82     2.65     5.36    ... -0.44773 -0.28832 -0.01581]
 [ 4.82     2.65     5.36    ... -0.43029 -0.28423 -0.01779]
 [ 4.82     2.65     5.36    ... -0.39028 -0.27518 -0.02313]]


In [ ]:
from sklearn_extra.cluster import KMedoids
kmedoids = KMedoids(n_clusters=2, random_state=0).fit(X1)

In [ ]:
kmedoids.labels_

In [ ]:
kmedoids.cluster_centers_